#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpipeline
Version  : 1.4.1
Release  : 8
URL      : http://nongnu.askapache.com/libpipeline/libpipeline-1.4.1.tar.gz
Source0  : http://nongnu.askapache.com/libpipeline/libpipeline-1.4.1.tar.gz
Summary  : Pipeline manipulation library
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: libpipeline-lib
Requires: libpipeline-doc
BuildRequires : pkgconfig(check)

%description
libpipeline, a pipeline manipulation library
============================================

%package dev
Summary: dev components for the libpipeline package.
Group: Development
Requires: libpipeline-lib

%description dev
dev components for the libpipeline package.


%package doc
Summary: doc components for the libpipeline package.
Group: Documentation

%description doc
doc components for the libpipeline package.


%package lib
Summary: lib components for the libpipeline package.
Group: Libraries

%description lib
lib components for the libpipeline package.


%prep
%setup -q -n libpipeline-1.4.1

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
